namespace Mediator.SourceGenerator.Helpers;

internal static class SourceGenerationHelper
{
    public const string Namespace = "Mediator";
    public const string AttributeName = "RegisterMediatorAttribute";

    public const string Attribute = $@"// <auto-generated/>

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class {AttributeName} : System.Attribute
    {{
    }}
}}";
}